'use strict';
const express = require('express');
const app = express();
const morgan = require('morgan');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
require('dotenv').config({silent: true});
const config = require('./../configs');
const passport = require('passport');
const cors = require('./../configs/middlewares/cors');
app.use(cookieParser());
app.use(cors);
app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(morgan('dev'));
app.use(helmet());
require('./../configs/bootstrap');
require('./../configs/db')(app, config);
require('./../configs/middlewares/passport')(passport);
app.use(passport.initialize());
require('./routes')(app);
module.exports = app;